server:
  port: 8100
  servlet:
    context-path: /redisTest
  max-http-header-size: 4048576
spring:
  datasource:
    url : jdbc:mysql://10.65.3.5:3306/kstp_guidance
    username : kstp_guidance
    password : 5vyndoRgxYQGMNkHOAqI+
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect

  http:
    encoding:
      charset: utf-8
  redis:
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
    jedis:
      pool:
        maxActive: 5000 #最大连接数
        maxIdle : 30 #最大空闲连接数
        minIdle : 5 #最小空闲连接数
        maxWait : 3000
    # 海豚redis外部访问地址
    password: kjZDxuBfXPaoWjEgS4kN
    host: 10.65.3.3
    port: 7396
    timeout: 5000
    session:
      store-type: redis
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true

#跨域
web.cors:
  enabled: true
  allowCredentials: true
  allowedOrigins:
    - '*'
  allowedHeaders:
    - '*'
  allowedMethods:
    - '*'